package com.am.crm.customer.domain;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.sql.Timestamp;
import java.util.UUID;

@Entity
@Table(name = "customers")
@Data
public class Customer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    private Long id;

    @NotBlank(message = "Name is required")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    @NotBlank(message = "Surname is required")
    @Size(min = 2, max = 100, message = "Surname must be between 2 and 100 characters")
    @Column(name = "surname", nullable = false, length = 100)
    private String surname;

    @NotNull(message = "Customer ID is required")
    @Column(name = "customer_id", unique = true, nullable = false, updatable = false)
    private UUID customerId;

    @Column(name = "photo_key")
    private String photoKey;

    @NotBlank(message = "Created by is required")
    @Column(name = "created_by", nullable = false, updatable = false)
    private String createdBy;

    @NotBlank(message = "Updated by is required")
    @Column(name = "updated_by", nullable = false)
    private String updatedBy;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private Timestamp createdAt; // Auto-generated by Hibernate

    @Column(name = "updated_at", nullable = false)
    @UpdateTimestamp
    private Timestamp updatedAt; // Auto-generated by Hibernate
}
