spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${GATEWAY_CLIENT_ID}
            client-secret: ${GATEWAY_CLIENT_SECRET}
        provider:
          cognito:
            issuer-uri: ${GATEWAY_ISSUER_URI}
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      httpclient:
        connect-timeout: 30000  # 30 seconds
        response-timeout: 60000  # 60 seconds
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**,/v1/users/**
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**,/v1/customers/**
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG