spring:
  main:
    web-application-type: reactive
  docker:
    compose:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ${GATEWAY_CLIENT_ID}
            client-secret: ${GATEWAY_CLIENT_SECRET}
        provider:
          cognito:
            issuer-uri: ${ISSUER_URI}
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      httpclient:
        connect-timeout: 30000  # 30 seconds
        response-timeout: 60000  # 60 seconds
      routes:
        - id: user-service
          uri: ${USER_SERVER_URI}:8081
          predicates:
            - Path=/users/**,/v1/users/**
        - id: customer-service
          uri: ${CUSTOMER_SERVER_URI}:8082
          predicates:
            - Path=/customers/**,/v1/customers/**
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG